version: '3.8'
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample-app
    volumes:
      - ../db/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    expose:
      - "3306"

  javascript:
    depends_on:
      - db
    build: ../javascript
    environment: 
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=root
    ports:
      - "3000:3000"
    restart: always
